package lvh.naheulbeuk.model.list;

public enum ActionType {
	MODIFY_D20_CARACT,
	MODIFY_CARACT,
	ADD_OBJECT,
	ADD_FOOD,
	REMOVE_FOOD,
	ADD_COMPANION,
	REMOVE_COMPANION,
	REMOVE_OBJECT,
	ADD_TEMPORARY,
	REMOVE_TEMPORARY,
	END;
}
