package lvh.naheulbeuk.model.list;

public enum EquipementType {
	SHIELD,
	CONTACT_WEAPON,
	DISTANCE_WEAPON,
	MAGIC_WEAPON,
	HEAD_PROTECTION,
	FOOT_PROTECTION,
	ARM_PROTECTION,
	TORAX_PROTECTION,
	FULL_PROTECTION,
	JEWLERY,
	RELIC
}
